name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Name of the enviroment (staging/production)"
        required: true
        default: "production"  

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: envrionment input
        run: echo "Environment:${{ inputs.environment }}"